services:
  frontend:
      container_name: crud-frontend
      build:
        context: ./client
      ports:
        - '80:80'
      depends_on:
        - backend
        - mongo

  backend:
    container_name: crud-backend
    build:
      context: ./server
    environment:
      DBUSER: usuariodev
      PASSWORD: 1234
      PORT: 3100
    ports:
      - '3100:3100'
    depends_on:
      - mongo

  mongo:
    container_name: database-mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuariodev
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongodbdata:/data/db
  
volumes:
  mongodbdata: